#!/bin/bash

# Define the base command using both production and dev override files.
# This ensures we use the local build (from dev.yml) instead of the GHCR image.
COMPOSE="docker compose -f docker-compose.yml -f docker-compose.dev.yml"
DEFAULT_APP_PORT=5353

# Keep local launches on a predictable address. APP_PORT may be overridden for
# a one-off run when another service already occupies the default port.
prepare_local_port() {
    if [ -z "${APP_PORT:-}" ]; then
        APP_PORT="$DEFAULT_APP_PORT"
        export APP_PORT
    fi

    # Keep links generated by the app usable for the standard local setup.
    env_file="${ENV_FILE:-.env}"
    configured_app_url=""
    if [ -z "${APP_URL:-}" ] && [ -f "$env_file" ]; then
        configured_app_url="$(sed -n 's/^APP_URL=//p' "$env_file" | head -n 1)"
    fi

    if [ -z "${APP_URL:-}" ] && \
       { [ -z "$configured_app_url" ] || [ "$configured_app_url" = "http://localhost:3000" ]; }; then
        APP_URL="http://localhost:${APP_PORT}"
        export APP_URL
    fi

    echo "Using app port: ${APP_PORT}"
}

show_help() {
    echo "Usage: ./compose.sh [command]"
    echo ""
    echo "Commands:"
    echo "  build   Build the images"
    echo "  start   Start the stack"
    echo "  restart Restart the stack"
    echo "  stop    Stop the stack"
    echo "  down    Stop and remove containers"
    echo ""
}

# If no arguments provided, show help.
if [ -z "$1" ]; then
    show_help
    exit 1
fi

case "$1" in
    start)
        prepare_local_port
        echo "Starting stack..."
        $COMPOSE up -d
        ;;
    restart)
        prepare_local_port
        echo "Restarting stack..."
        $COMPOSE down
        $COMPOSE up -d
        ;;
    stop)
        echo "Stopping stack..."
        $COMPOSE stop
        ;;
    down)
        echo "Tearing down stack..."
        $COMPOSE down
        ;;
    build)
        echo "Building stack..."
        $COMPOSE build
        ;;
    *)
        echo "Error: Unknown command '$1'"
        show_help
        exit 1
        ;;
esac
